name: Deploy to Vercel on main push

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Vercel Deployment
              run: |
                  if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                      curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_1588LrPqxxFZuZeH2kUc5VNEFze1/JcGJrnAXx6
                  fi